#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
##################################################
#
# ECP 3004: Python for Business Analytics
#
# Name: Zaid Mushtaq
#
# Date: 3/8/21
# 
##################################################
#
# Test script for midterm
#
##################################################
"""

##################################################
# Import Required Modules
##################################################

import os
import doctest


##################################################
# Set Working Directory.
##################################################


# Find out the current directory.
os.getcwd()
# Change to a new directory.
os.chdir('/Users/zaidmushtaq/ECP3004S21/midterm_exam')
# Check that the change was successful.
os.getcwd()



##################################################
# Read script and test.
##################################################


# Read the script my_A5_functions.py to run the tests. 
exec(open("my_midterm_module.py").read())


doctest.testmod()



##################################################
# Import your module and use it on some examples
##################################################

# Optional (not graded): 
# Use this as a scratchpad to test your functions
# and print out results.

# Get your testing it out of your system here and 
# keep the printing and testing out of the 
# my_A4_functions module. 


import my_midterm_module as mmm

# Insert examples like this for any tests you want to try.
mmm.in_budget(3, 1, 10, 25, 100)
mmm.in_budget(2, 2, 15, 20, 100)
mmm.in_budget(5, 3, 10, 25, 100)
mmm.calc_bundle(10, 20, 120, 1.0/3.0)
mmm.calc_bundle(10, 25, 100, .5)
mmm.calc_bundle(10, 25, 100, 2.0/3.0)
mmm.y_solve(5, 5, 10, 100)
mmm.y_solve(5, 10, 25, 100)
mmm.y_solve(7, 10, 25, 100)
mmm.one_loop_bundle(5, 10, 100, 0.25, 0.01)
mmm.one_loop_bundle(10, 25, 100, .5, .1)
mmm.one_loop_bundle(25, 25, 100, .5, .1)
mmm.util_in_budget(4, 4, 10, 20, 120, 1.0/3.0)
mmm.util_in_budget(2, 2, 25, 25, 100, .5)
mmm.util_in_budget(-1, 4, 100, 100, 100, .5)
mmm.util_in_budget(4, -1, 100, 100, 100, .5)
mmm.util_in_budget(4, 4, 100, 100, 100, 1.1)
mmm.two_loop_bundle(10, 25, 100, 0.5, 0.01)
mmm.two_loop_bundle(25, 25, 100, .5, .01)
mmm.two_loop_bundle(10, 20, 120, 1.0/3.0, .01)


##################################################
# End
##################################################